### ISSUE TITLE
Drag & Drop of different files leads sometimes to errors. Restarting BLITZ solves it

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#20]
Traceback (most recent call last):
  File "C:\INP\Projekte\Python\BLITZ\blitz\layout\main.py", line 543, in load_images
    self.image_viewer.load_data(
  File "C:\INP\Projekte\Python\BLITZ\blitz\layout\viewer.py", line 94, in load_data
    self.setImage(self.data.image)
  File "C:\Users\Mattern\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyqtgraph\imageview\ImageView.py", line 322, in setImage
    raise TypeError("Image must be NumPy array or any object "
TypeError: Image must be NumPy array or any object that provides compatible attributes/methods:
  ['dtype', 'max', 'min', 'ndim', 'shape', 'size']

**Comment by irkri** [comment]
Can you test this again for PR #21? This should be fixed by the new file loading system.

**Comment by PiMaV** [comment]
Not reproducable anymore...
